blank_issues_enabled: true
contact_links:
  - name: Problema de seguridad
    url: https://github.com/owellandry/mclaunch/security
    about: Reporta vulnerabilidades de forma privada a traves de la pagina de seguridad cuando este disponible.
