/**
 * @file versionArt.ts
 * @description Maps every Minecraft *release* version to local high-res key art.
 *
 * Images: public/version-art/{versionId}.{ext}
 * Generated by: pnpm download-art  (scripts/download-version-art.mjs)
 *
 * The manifest is a full versionId → filename map for all Mojang releases.
 * Unknown / future versions fall back to the highest art key ≤ that version
 * by scanning known keys from the manifest values' sources via inheritance
 * on the version ids themselves.
 */

import artManifest from "./versionArt.manifest.json";

const ART_BY_VERSION: Record<string, string> = artManifest as Record<
  string,
  string
>;

function parseVersionParts(version: string): number[] {
  const core = version.split("-")[0]?.split("+")[0] ?? version;
  return core.split(".").map((part) => {
    const n = parseInt(part, 10);
    return Number.isFinite(n) ? n : 0;
  });
}

/** Compare dotted Minecraft version ids. Negative if a < b. */
export function compareMinecraftVersions(a: string, b: string): number {
  const pa = parseVersionParts(a);
  const pb = parseVersionParts(b);
  const len = Math.max(pa.length, pb.length);
  for (let i = 0; i < len; i++) {
    const diff = (pa[i] ?? 0) - (pb[i] ?? 0);
    if (diff !== 0) return diff;
  }
  return 0;
}

/**
 * Exact match, or nearest lower covered release (for new patches not yet in the
 * committed manifest). Snapshots return null.
 */
export function resolveArtKey(versionId: string): string | null {
  if (!versionId) return null;
  if (/^\d{2,}w\d{2,}[a-z]?$/i.test(versionId)) return null;

  if (ART_BY_VERSION[versionId]) return versionId;

  const known = Object.keys(ART_BY_VERSION).sort(compareMinecraftVersions);
  let best: string | null = null;
  for (const key of known) {
    if (compareMinecraftVersions(key, versionId) <= 0) {
      best = key;
    }
  }
  return best;
}

/** Public URL for the version key art, or null if unmapped. */
export function getVersionArt(versionId: string): string | null {
  if (!versionId) return null;

  const exact = ART_BY_VERSION[versionId];
  if (exact) return `/version-art/${exact}`;

  const fallbackId = resolveArtKey(versionId);
  if (!fallbackId) return null;
  const file = ART_BY_VERSION[fallbackId];
  if (!file) return null;
  return `/version-art/${file}`;
}

export function getVersionArtManifest(): Record<string, string> {
  return { ...ART_BY_VERSION };
}

/** Number of release versions with committed art (for diagnostics). */
export function getVersionArtCoverageCount(): number {
  return Object.keys(ART_BY_VERSION).length;
}
